// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/dev-hyunsang/clone-twitter-backend/ent/schema"
	"github.com/dev-hyunsang/clone-twitter-backend/ent/user"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUserUUID is the schema descriptor for user_uuid field.
	userDescUserUUID := userFields[0].Descriptor()
	// user.DefaultUserUUID holds the default value on creation for the user_uuid field.
	user.DefaultUserUUID = userDescUserUUID.Default.(func() uuid.UUID)
	// userDescUserEmail is the schema descriptor for user_email field.
	userDescUserEmail := userFields[1].Descriptor()
	// user.DefaultUserEmail holds the default value on creation for the user_email field.
	user.DefaultUserEmail = userDescUserEmail.Default.(string)
	// userDescUserPhoneNumber is the schema descriptor for user_phone_number field.
	userDescUserPhoneNumber := userFields[2].Descriptor()
	// user.DefaultUserPhoneNumber holds the default value on creation for the user_phone_number field.
	user.DefaultUserPhoneNumber = userDescUserPhoneNumber.Default.(string)
	// userDescUserPassword is the schema descriptor for user_password field.
	userDescUserPassword := userFields[3].Descriptor()
	// user.DefaultUserPassword holds the default value on creation for the user_password field.
	user.DefaultUserPassword = userDescUserPassword.Default.(string)
	// userDescUserBirthday is the schema descriptor for user_birthday field.
	userDescUserBirthday := userFields[4].Descriptor()
	// user.DefaultUserBirthday holds the default value on creation for the user_birthday field.
	user.DefaultUserBirthday = userDescUserBirthday.Default.(string)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[5].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[6].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
}
